Launch Form Msgpack IDL Supporting
flyteorg/flyteconsole pull request #888
Opened 2024-10-14 23:41 UTC by lyonlu13

# TL;DR
Add msgpack IDL support for the launch form, including input displaying and relaunch input recovering.
<img width="814" alt="image" src="https://github.com/user-attachments/assets/cef8a14b-20b3-4240-82a2-fbde78739d17">
<img width="578" alt="image" src="https://github.com/user-attachments/assets/cfbf79c9-1990-4097-af82-8145b123f8a7">

## Type
 - [ ] Bug Fix
 - [x] Feature
 - [ ] Plugin

2024-10-15 16:51 UTC, ursucarina requested changes

2024-10-15 16:51 UTC, ursucarina commented on packages/oss-console/src/components/Literals/helpers.ts
> +    return {
should we still return the tag and an undefined value when `binary.value` is undefined?

2024-10-15 16:51 UTC, ursucarina commented on packages/oss-console/src/components/Launch/LaunchForm/LaunchFormComponents/StructInput.tsx
> +      const value = initialValue.scalar?.binary?.value;
instead of having this here, please update `/inputHelpers/utils.ts`->`fromLiteral` to correctly parse the value. Currently that will throw an error

2024-10-16 19:25 UTC, ursucarina submitted a review, later dismissed

2024-10-17 21:23 UTC, ursucarina approved these changes

2024-10-17 21:23 UTC, merged

2024-10-17 21:59 UTC, eapolinario commented on packages/oss-console/src/components/Launch/LaunchForm/inputHelpers/struct.ts
> +  return '';
Any reason not to stringify `binary.value` and return that instead?